name: Run Scraper

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install requests beautifulsoup4 tqdm aiohttp

      - name: Run scraper
        run: python main.py

      - name: Commit & push data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data/
          git commit -m "Update data" || echo "No changes"
          git push
